@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/user
Content-Type: application/json

{
  "name":"Fernando Pessoa",
  "email": "fernandopessoa@gmail.com",
  "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "fernandopessoa@gmail.com",
  "password": "123456"
}

###

# @name update_profile_image
PATCH {{baseUrl}}/my-image
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "profileImage": "nova foto 2.0"
}

###

# @name update_user_name
PATCH {{baseUrl}}/my-name
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "userName": "marcelinho"
}

###

# @name send_email
POST {{baseUrl}}/email
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Frases",
  "content": "Nao sei quantas almas tenho. Cada momento mudei",
  "emailDeDestinatario": "anddrecosttascheffer@gmail.com"
}